"""Add email_verified to User model

Revision ID: 04e6f26b153f
Revises: 
Create Date: 2025-07-04 11:02:24.686942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04e6f26b153f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('email_verification_code', sa.String(length=6), nullable=True))
        batch_op.add_column(sa.Column('email_verification_expires', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('reset_password_code', sa.String(length=6), nullable=True))
        batch_op.add_column(sa.Column('reset_password_expires', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('reset_password_expires')
        batch_op.drop_column('reset_password_code')
        batch_op.drop_column('email_verification_expires')
        batch_op.drop_column('email_verification_code')
        batch_op.drop_column('email_verified')

    # ### end Alembic commands ###
